/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import model.Cilindro;
import model.Cone;
import model.Esfera;
import model.Paralelepipedo;
import model.Piramide;
import model.Retangulo;

/**
 *
 * @author eduardohilario
 */
public class App extends javax.swing.JFrame {

    Cilindro cilindro = new Cilindro();
    Cone cone = new Cone();
    Esfera esfera = new Esfera();
    Paralelepipedo paralelepipedo = new Paralelepipedo();
    Piramide piramide = new Piramide();
    Retangulo retangulo = new Retangulo();

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        inputRaioCilindro = new javax.swing.JTextField();
        inputAlturaCilindro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        saidaCilindro = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputRaioCone = new javax.swing.JTextField();
        inputAlturaCone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        saidaCone = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputRaioEsfera = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        saidaEsfera = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inputAlturaPara = new javax.swing.JTextField();
        inputLarguraPara = new javax.swing.JTextField();
        inputCompPara = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        saidaPara = new javax.swing.JTextArea();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        inputBasePira = new javax.swing.JTextField();
        inputAlturaPira = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        saidaPira = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        inputLarguraRet = new javax.swing.JTextField();
        inputCompRet = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        saidaRet = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>\nFiguras<br>\nGeométricas</center>\n</html>");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/figuras.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cilindro.png"))); // NOI18N
        jLabel3.setText("Cilindro");

        inputRaioCilindro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputRaioCilindroKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputRaioCilindroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputRaioCilindroKeyReleased(evt);
            }
        });

        inputAlturaCilindro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputAlturaCilindroKeyReleased(evt);
            }
        });

        jLabel4.setText("Raio:");

        jLabel5.setText("Altura:");

        saidaCilindro.setEditable(false);
        saidaCilindro.setColumns(20);
        saidaCilindro.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        saidaCilindro.setLineWrap(true);
        saidaCilindro.setRows(5);
        jScrollPane1.setViewportView(saidaCilindro);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cone.png"))); // NOI18N
        jLabel6.setText("Cone");

        jLabel7.setText("Raio:");

        jLabel8.setText("Altura:");

        inputRaioCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRaioConeActionPerformed(evt);
            }
        });
        inputRaioCone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputRaioConeKeyReleased(evt);
            }
        });

        inputAlturaCone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputAlturaConeKeyReleased(evt);
            }
        });

        saidaCone.setEditable(false);
        saidaCone.setColumns(20);
        saidaCone.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        saidaCone.setLineWrap(true);
        saidaCone.setRows(5);
        jScrollPane2.setViewportView(saidaCone);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/esfera.png"))); // NOI18N
        jLabel9.setText("Esfera");

        jLabel10.setText("Raio:");

        inputRaioEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRaioEsferaActionPerformed(evt);
            }
        });
        inputRaioEsfera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputRaioEsferaKeyReleased(evt);
            }
        });

        saidaEsfera.setEditable(false);
        saidaEsfera.setColumns(20);
        saidaEsfera.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        saidaEsfera.setLineWrap(true);
        saidaEsfera.setRows(5);
        jScrollPane3.setViewportView(saidaEsfera);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paralelepipedo.png"))); // NOI18N
        jLabel11.setText("Paralelepípedo");

        jLabel12.setText("Altura:");

        jLabel13.setText("Largura:");

        jLabel14.setText("Comprimento:");

        inputAlturaPara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputAlturaParaKeyReleased(evt);
            }
        });

        inputLarguraPara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputLarguraParaKeyReleased(evt);
            }
        });

        inputCompPara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCompParaKeyReleased(evt);
            }
        });

        saidaPara.setEditable(false);
        saidaPara.setColumns(20);
        saidaPara.setLineWrap(true);
        saidaPara.setRows(5);
        jScrollPane4.setViewportView(saidaPara);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/piramide.gif"))); // NOI18N
        jLabel15.setText("Piramide");

        jLabel16.setText("Base:");

        jLabel17.setText("Altura:");

        inputBasePira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputBasePiraKeyReleased(evt);
            }
        });

        inputAlturaPira.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputAlturaPiraKeyReleased(evt);
            }
        });

        saidaPira.setEditable(false);
        saidaPira.setColumns(20);
        saidaPira.setLineWrap(true);
        saidaPira.setRows(5);
        scroll.setViewportView(saidaPira);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retangulo.png"))); // NOI18N
        jLabel18.setText("Retângulo");

        jLabel19.setText("Largura:");

        jLabel20.setText("Comprimento:");

        inputLarguraRet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputLarguraRetKeyReleased(evt);
            }
        });

        inputCompRet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCompRetKeyReleased(evt);
            }
        });

        saidaRet.setEditable(false);
        saidaRet.setColumns(20);
        saidaRet.setLineWrap(true);
        saidaRet.setRows(5);
        jScrollPane6.setViewportView(saidaRet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCompRet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputLarguraRet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputAlturaPira, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputBasePira, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)
                                .addGap(33, 33, 33)
                                .addComponent(inputRaioEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(inputRaioCone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputAlturaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputRaioCilindro)
                                    .addComponent(inputAlturaCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCompPara, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputLarguraPara, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAlturaPara, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel4)
                                    .addComponent(inputRaioCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel5)
                                    .addComponent(inputAlturaCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel7)
                                    .addComponent(inputRaioCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel8)
                                    .addComponent(inputAlturaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(inputRaioEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(inputAlturaPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(inputLarguraPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(inputCompPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(inputBasePira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(inputAlturaPira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(inputLarguraRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel20)
                                    .addComponent(inputCompRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel18)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputRaioCilindroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRaioCilindroKeyTyped

    }//GEN-LAST:event_inputRaioCilindroKeyTyped

    private void inputRaioCilindroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRaioCilindroKeyPressed

    }//GEN-LAST:event_inputRaioCilindroKeyPressed

    private void inputRaioCilindroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRaioCilindroKeyReleased
        try {
            cilindro.setRaio(Float.parseFloat(inputRaioCilindro.getText()));

        } catch (Exception ex) {
            Msg.validaNegativo();
            saidaCilindro.setText("");
                inputAlturaCilindro.setText("");
                inputRaioCilindro.setText("");
        }
        if (inputAlturaCilindro.getText().equalsIgnoreCase("")) {
            saidaCilindro.setText("Informe a altura do Cilindro");
        } else {
            saidaCilindro.setText(cilindro.calculosToString());
        }


    }//GEN-LAST:event_inputRaioCilindroKeyReleased

    private void inputAlturaCilindroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAlturaCilindroKeyReleased
        try {
                cilindro.setAltura(Float.parseFloat(inputAlturaCilindro.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaCilindro.setText("");
                inputAlturaCilindro.setText("");
                inputRaioCilindro.setText("");
            }
        if (inputRaioCilindro.getText().equalsIgnoreCase("")) {
            saidaCilindro.setText("Informe o raio do Cilindro");
        } else {
            saidaCilindro.setText(cilindro.calculosToString());
        }
    }//GEN-LAST:event_inputAlturaCilindroKeyReleased

    private void inputRaioConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRaioConeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRaioConeActionPerformed

    private void inputRaioConeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRaioConeKeyReleased
        try {
            cone.setRaio(Float.parseFloat(inputRaioCone.getText()));

        } catch (Exception ex) {
            Msg.validaNegativo();
            saidaCone.setText("");
                inputRaioCone.setText("");
                inputAlturaCone.setText("");
        }
        if (inputAlturaCone.getText().equalsIgnoreCase("")) {
            saidaCone.setText("Informe a altura do Cone");
        } else {
            saidaCone.setText(cone.calculosToString());
        }
    }//GEN-LAST:event_inputRaioConeKeyReleased

    private void inputAlturaConeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAlturaConeKeyReleased
        try {
                cone.setAltura(Float.parseFloat(inputAlturaCone.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaCone.setText("");
                inputAlturaCone.setText("");
                inputRaioCone.setText("");
            }
        if (inputRaioCone.getText().equalsIgnoreCase("")) {
            saidaCone.setText("Informe o raio do Cone");
        } else {
            saidaCone.setText(cone.calculosToString());
        }
    }//GEN-LAST:event_inputAlturaConeKeyReleased

    private void inputRaioEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRaioEsferaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRaioEsferaActionPerformed

    private void inputRaioEsferaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRaioEsferaKeyReleased
        try {
            esfera.setRaio(Float.parseFloat(inputRaioEsfera.getText()));
            saidaEsfera.setText(esfera.calculosToString());
        } catch (Exception ex) {
            Msg.validaNegativo();
            inputRaioEsfera.setText("");
            saidaEsfera.setText("");
        }
       
    }//GEN-LAST:event_inputRaioEsferaKeyReleased

    private void inputAlturaParaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAlturaParaKeyReleased
        try {
                paralelepipedo.setAltura(Float.parseFloat(inputAlturaPara.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaPara.setText("");
                inputAlturaPara.setText("");
                inputCompPara.setText("");
                inputLarguraPara.setText("");
            }
        if (inputLarguraPara.getText().equalsIgnoreCase("") || inputCompPara.getText().equalsIgnoreCase("")) {
            saidaPara.setText("Informe os dados do paralelepipedo");
        } else {
            saidaPara.setText(paralelepipedo.calculosToString());
        }
    }//GEN-LAST:event_inputAlturaParaKeyReleased

    private void inputLarguraParaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputLarguraParaKeyReleased
        try {
                paralelepipedo.setLargura(Float.parseFloat(inputLarguraPara.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaPara.setText("");
                inputAlturaPara.setText("");
                inputCompPara.setText("");
                inputLarguraPara.setText("");
            }
        if (inputAlturaPara.getText().equalsIgnoreCase("") || inputCompPara.getText().equalsIgnoreCase("")) {
            saidaPara.setText("Informe os dados do paralelepipedo");
        } else {
            saidaPara.setText(paralelepipedo.calculosToString());
        }
    }//GEN-LAST:event_inputLarguraParaKeyReleased

    private void inputCompParaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCompParaKeyReleased
        try {
                paralelepipedo.setComprimento(Float.parseFloat(inputCompPara.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaPara.setText("");
                inputAlturaPara.setText("");
                inputCompPara.setText("");
                inputLarguraPara.setText("");
            }
        if (inputAlturaPara.getText().equalsIgnoreCase("") || inputLarguraPara.getText().equalsIgnoreCase("")) {
            saidaPara.setText("Informe os dados do paralelepipedo");
        } else {
            saidaPara.setText(paralelepipedo.calculosToString());
        }
    }//GEN-LAST:event_inputCompParaKeyReleased

    private void inputBasePiraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputBasePiraKeyReleased
        try {
                piramide.setBase(Float.parseFloat(inputBasePira.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaPira.setText("");
                inputBasePira.setText("");
                inputAlturaPira.setText("");
            }
        if (inputAlturaPira.getText().equalsIgnoreCase("")) {
            saidaPira.setText("Informe a base da piramide");
        } else {
            saidaPira.setText(piramide.calculosToString());
        }
    }//GEN-LAST:event_inputBasePiraKeyReleased

    private void inputAlturaPiraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAlturaPiraKeyReleased
        try {
                piramide.setAltura(Float.parseFloat(inputAlturaPira.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaPira.setText("");
                inputBasePira.setText("");
                inputAlturaPira.setText("");
            }
        if (inputBasePira.getText().equalsIgnoreCase("")) {
            saidaPira.setText("Informe a base da piramide");
        } else {
            saidaPira.setText(piramide.calculosToString());
        }
    }//GEN-LAST:event_inputAlturaPiraKeyReleased

    private void inputLarguraRetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputLarguraRetKeyReleased
        try {
                retangulo.setLargura(Float.parseFloat(inputLarguraRet.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaRet.setText("");
                inputCompRet.setText("");
                inputLarguraRet.setText("");
            }
        if (inputCompRet.getText().equalsIgnoreCase("")) {
            saidaRet.setText("Informe o comprimento do retângulo");
        } else {
            saidaRet.setText(retangulo.calculosToString());
        }
    }//GEN-LAST:event_inputLarguraRetKeyReleased

    private void inputCompRetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCompRetKeyReleased
        try {
                retangulo.setComprimento(Float.parseFloat(inputCompRet.getText()));
                
            } catch (Exception ex) {
                Msg.validaNegativo();
                saidaRet.setText("");
                inputCompRet.setText("");
                inputLarguraRet.setText("");
            }
        if (inputLarguraRet.getText().equalsIgnoreCase("")) {
            saidaRet.setText("Informe a largura do retângulo");
        } else {
            saidaRet.setText(retangulo.calculosToString());
        }
    }//GEN-LAST:event_inputCompRetKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputAlturaCilindro;
    private javax.swing.JTextField inputAlturaCone;
    private javax.swing.JTextField inputAlturaPara;
    private javax.swing.JTextField inputAlturaPira;
    private javax.swing.JTextField inputBasePira;
    private javax.swing.JTextField inputCompPara;
    private javax.swing.JTextField inputCompRet;
    private javax.swing.JTextField inputLarguraPara;
    private javax.swing.JTextField inputLarguraRet;
    private javax.swing.JTextField inputRaioCilindro;
    private javax.swing.JTextField inputRaioCone;
    private javax.swing.JTextField inputRaioEsfera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea saidaCilindro;
    private javax.swing.JTextArea saidaCone;
    private javax.swing.JTextArea saidaEsfera;
    private javax.swing.JTextArea saidaPara;
    private javax.swing.JTextArea saidaPira;
    private javax.swing.JTextArea saidaRet;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
